(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'Field' object has no attribute 'naam'"
p3
sS'layer'
p4
S'C:\\Users\\Pieter-Jan\\PycharmProjects\\untitled\\web2py\\applications\\Sensors\\controllers/detail.py'
p5
sS'code'
p6
S'import matplotlib.pyplot as plt\n\n\ndef index():\n    sensorNaam = request.vars[\'naam\']\n    rows = db(db.data.sensor.naam == sensorNaam).select()\n    #plt.plot(rows)\n    #plt.ylabel(\'some numbers\')\n    #plt.show()\n    return dict(hello="Hello")\n\nresponse._vars=response._caller(index)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "C:\\Users\\Pieter-Jan\\PycharmProjects\\untitled\\web2py\\gluon\\restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "C:\\Users\\Pieter-Jan\\PycharmProjects\\untitled\\web2py\\applications\\Sensors\\controllers/detail.py", line 12, in <module>\n  File "C:\\Users\\Pieter-Jan\\PycharmProjects\\untitled\\web2py\\gluon\\globals.py", line 417, in <lambda>\n    self._caller = lambda f: f()\n  File "C:\\Users\\Pieter-Jan\\PycharmProjects\\untitled\\web2py\\applications\\Sensors\\controllers/detail.py", line 6, in index\n    rows = db(db.data.sensor.naam == sensorNaam).select()\nAttributeError: \'Field\' object has no attribute \'naam\'\n'
p11
s.