(dp1
S'output'
p2
S"<class 'plotly.exceptions.PlotlyDictKeyError'> 'y' is not allowed in 'line'\n\nPath To Error: ['y']\n\nValid attributes for 'line' at path [] under parents []:\n\n    ['colorsrc', 'autocolorscale', 'cmin', 'outliercolor', 'colorscale',\n    'color', 'simplify', 'smoothing', 'reversescale', 'width', 'shape',\n    'cauto', 'outlierwidth', 'widthsrc', 'showscale', 'cmax', 'dash']\n\nRun `<line-object>.help('attribute')` on any of the above.\n'<line-object>' is the object at []"
p3
sS'layer'
p4
S'C:\\Users\\Pieter-Jan\\PycharmProjects\\untitled\\web2py\\applications\\Sensors\\controllers/overzicht.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\n# probeer zoiets als\n\nimport plotly.plotly as py\nfrom plotly.graph_objs import Data, Line\n#py.tools.set_credentials_file(username=\'epicfacexp\', api_key=\'2j3arysr66\')\n\n\ndef index():\n    rows = db(db.sensor.id > 0).select()\n    return dict(message="hello from overzicht.py", rijen=rows)\n\n\ndef detail():\n    print("detail() in overzicht.py")\n    sensorNaam = request.vars[\'naam\']\n    time = db(db.data.sensor == sensorNaam).select(db.data.tijd)\n    temp = db(db.data.sensor == sensorNaam).select(db.data.temperatuur)\n\n    trace0 = Line(\n        x=time,\n        y=temp\n    )\n    data = Data([trace0])\n\n    url = py.plot(data, filename=\'basic-line\')\n\n    return dict(dataset="url")\n\nresponse._vars=response._caller(detail)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "C:\\Users\\Pieter-Jan\\PycharmProjects\\untitled\\web2py\\gluon\\restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "C:\\Users\\Pieter-Jan\\PycharmProjects\\untitled\\web2py\\applications\\Sensors\\controllers/overzicht.py", line 30, in <module>\n  File "C:\\Users\\Pieter-Jan\\PycharmProjects\\untitled\\web2py\\gluon\\globals.py", line 417, in <lambda>\n    self._caller = lambda f: f()\n  File "C:\\Users\\Pieter-Jan\\PycharmProjects\\untitled\\web2py\\applications\\Sensors\\controllers/overzicht.py", line 22, in detail\n    y=temp\n  File "C:\\Python27\\lib\\site-packages\\plotly\\graph_objs\\graph_objs.py", line 375, in __init__\n    self.__setitem__(key, val, _raise=_raise)\n  File "C:\\Python27\\lib\\site-packages\\plotly\\graph_objs\\graph_objs.py", line 426, in __setitem__\n    raise exceptions.PlotlyDictKeyError(self, path)\nPlotlyDictKeyError: \'y\' is not allowed in \'line\'\n\nPath To Error: [\'y\']\n\nValid attributes for \'line\' at path [] under parents []:\n\n    [\'colorsrc\', \'autocolorscale\', \'cmin\', \'outliercolor\', \'colorscale\',\n    \'color\', \'simplify\', \'smoothing\', \'reversescale\', \'width\', \'shape\',\n    \'cauto\', \'outlierwidth\', \'widthsrc\', \'showscale\', \'cmax\', \'dash\']\n\nRun `<line-object>.help(\'attribute\')` on any of the above.\n\'<line-object>\' is the object at []\n'
p11
s.