(dp1
S'output'
p2
S"<type 'exceptions.ValueError'> setting an array element with a sequence."
p3
sS'layer'
p4
S'C:\\Users\\Pieter-Jan\\PycharmProjects\\untitled\\web2py\\applications\\Sensors\\controllers/overzicht.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\n# probeer zoiets als\nimport matplotlib.pyplot as plt\n\n\ndef index():\n    rows = db(db.sensor.id > 0).select()\n    return dict(message="hello from overzicht.py", rijen=rows)\n\n\ndef detail():\n    sensorNaam = request.vars[\'naam\']\n    time = db(db.data.sensor == sensorNaam).select(db.data.tijd)\n    temp = db(db.data.sensor == sensorNaam).select(db.data.temperatuur)\n    lines = plt.plot(temp, time)\n    return dict(data=lines)\n\nresponse._vars=response._caller(detail)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "C:\\Users\\Pieter-Jan\\PycharmProjects\\untitled\\web2py\\gluon\\restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "C:\\Users\\Pieter-Jan\\PycharmProjects\\untitled\\web2py\\applications\\Sensors\\controllers/overzicht.py", line 18, in <module>\n  File "C:\\Users\\Pieter-Jan\\PycharmProjects\\untitled\\web2py\\gluon\\globals.py", line 417, in <lambda>\n    self._caller = lambda f: f()\n  File "C:\\Users\\Pieter-Jan\\PycharmProjects\\untitled\\web2py\\applications\\Sensors\\controllers/overzicht.py", line 15, in detail\n    lines = plt.plot(temp, time)\n  File "C:\\Python27\\lib\\site-packages\\matplotlib\\pyplot.py", line 3161, in plot\n    ret = ax.plot(*args, **kwargs)\n  File "C:\\Python27\\lib\\site-packages\\matplotlib\\__init__.py", line 1819, in inner\n    return func(ax, *args, **kwargs)\n  File "C:\\Python27\\lib\\site-packages\\matplotlib\\axes\\_axes.py", line 1383, in plot\n    self.add_line(line)\n  File "C:\\Python27\\lib\\site-packages\\matplotlib\\axes\\_base.py", line 1703, in add_line\n    self._update_line_limits(line)\n  File "C:\\Python27\\lib\\site-packages\\matplotlib\\axes\\_base.py", line 1725, in _update_line_limits\n    path = line.get_path()\n  File "C:\\Python27\\lib\\site-packages\\matplotlib\\lines.py", line 938, in get_path\n    self.recache()\n  File "C:\\Python27\\lib\\site-packages\\matplotlib\\lines.py", line 625, in recache\n    x = np.asarray(xconv, np.float_)\n  File "C:\\Python27\\lib\\site-packages\\numpy\\core\\numeric.py", line 482, in asarray\n    return array(a, dtype, copy=False, order=order)\nValueError: setting an array element with a sequence.\n'
p11
s.